### ISSUE TITLE
Can't download rar files in the folder

### ISSUE THREAD

**Issue by softwareguild0** [Saief1999/sendcm-downloader#2]
Hello, I am trying to donwload a folder in send.cm which has rar files inside it. But for some reason the colab file doesn't download that. I have ran all the commands and it's throwing the following error. Can you please tell me what's the problem? Thanks.
I am trying to download this folder: https://send.cm/s/1QA6/React_Tutorial_and_Projects_Course_2022

![image](https://user-images.githubusercontent.com/111287559/204119806-b1d01748-4fd0-42dc-8707-32fa99d43f3a.png)

**Comment by Saief1999** [comment]
Hello, sorry for the late reply. I'll give it a look and let you know.

**Comment by Saief1999** [comment]
Check #3
