### ISSUE TITLE
Error loading page!

### ISSUE THREAD

**Issue by PhanTinhKhang** [Saief1999/sendcm-downloader#3]
i got error loading page when try to download a folder 
![image](https://user-images.githubusercontent.com/105924724/208665535-e37831b6-eb73-4f0d-90c4-1363a5a0dc8f.png)

**Comment by Saief1999** [comment]
Sorry for the late reply! Can you send me the link in question so I can test it from my end?

**Comment by Saief1999** [comment]
Send.cm is now using `cloudflare` so this script won't be able to hit the website directly. You're open to use a `cloudflare` bypasser if you'd like. But use it at your own risk.
